### ISSUE TITLE
"Tau-Prolog Behavior › Evaluates the maplist/3 Function Correctly" fails

### ISSUE THREAD

**Issue by Khazuar** [diproche/webinterface#24]
Expected value to equal:
      ["X = [2,3,4] ;", "false."]
Received:
      ["uncaught exception: error(existence_error(procedure, '/'(maplist, 3)), '/'(top_level, 0))", "false."]

**Comment by TimothyGillespie** [comment]
I initially included this into the tests as a more specific function. I knew it returned an error and left it in thinking it would remind that this function isn't implemented. I was didn't know that test should pass if the program is working as intended.

If a predicate is not implemented by tau-prolog it can be defined by oneself and be imported.
If a standard library cannot be imported the library can be found here:
http://www.swi-prolog.org/pldoc/doc_for?object=manual

Use the search function to find the standard library or needed function.
The libraries' source code can be accessed by clicking on the :- symbol circled in red:
![prologDocumentation](https://user-images.githubusercontent.com/17751957/58435478-fd1b1f00-80c0-11e9-9267-d1ae77515d08.JPG)

In this example you will be brought to this page:
http://www.swi-prolog.org/pldoc/doc/_SWI_/library/apply.pl?show=src#maplist/3

The current functionalities don't support an easy import of predicates defined by themselves neither do they evaluate library import calls for libraries not supported by tau-prolog. So if this is needed such thing should be implemented.


Here some advice on how to possibly do this:

For self-defined in-built predicates one could put them in a file which will be attached before the program string. An example for a built-in predicate which is not supported by tau-prolog would be the plus/3 predicate. Since these should only add predicates which are built-in it wouldn't be necessary to avoid name collisions.

For library imports the library `name` should be imported and loaded when the `:-use_module(library(name)).` is found. Please watch copyrights in these cases.
